circular/userprofile/urls.py
'''
Local file for the links to the user profile.
This is called int he main urls file of the project.
'''
from django.conf.urls import patterns, url

from userprofile import views

urlpatterns = patterns(  # pylint: disable=C0103
    '',
    url(r'^edit/$',
        views.update_profile,
        name='userprofile_edit_profile'),
    url(r'^$',
        views.ditail_profile,
        name='userprofile_ditail_profile'),
)

circular/weeklycircular/urls.py
'''
This is the main uarls file
'''

from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns(  # pylint: disable=C0103
    '',
    url(r'^password_change/$',
        'django.contrib.auth.views.password_change',
        {}, name='password_change'),
    url(r'^password_change_done/$',
        'django.contrib.auth.views.password_change_done',
        {}, name='password_change_done'),
    url(r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        {}, 'password_reset'),
    url(r'^password_reset_done/$',
        'django.contrib.auth.views.password_reset_done',
        {}, 'password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>.+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {}, 'password_reset_confirm'),
    url(r'^password_reset_complete/$',
        'django.contrib.auth.views.password_reset_complete',
        {}, 'password_reset_complete'),
    url(r'^accounts/profile/', include('userprofile.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'circular.views.home', name='home'),
    url(r'^about/$', 'circular.views.about', name='about'),
    url(r'^contact/$', 'circular.views.contact', name='contact'),
    url(r'^deals/$', 'circular.views.deals', name='deals'),
    url(r'^recipe/$', 'recipe.views.get_recipe', name='recipe'),
    url(r'^deals/(?P<store_id>[0-9]+)/$',
        'circular.views.store_locations',
        name='locations'),
    url(r'^deals/(?P<store_id>[0-9]+)/(?P<location_id>[0-9]+)/$',
        'circular.views.products',
        name='products'),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

circular/circular/models.py
'''This module is for adding models and fields to the form'''
from django.db import models

class Store(models.Model):
    '''
    This model is for the store her we
    have one store with the store name and a logo.
    '''
    store_name = models.CharField(max_length=128) #Field for storename eg.shop
    store_logo = models.CharField(
        max_length=512,
        null=True,
        blank=True
        )
    objects = models.Manager() # pylint: disable=E1120
    # Field to hold the store logo

    def __unicode__(self):
        return self.store_name

class StoreLocation(models.Model):
    '''
    Each store can have multiple location. so we have
    this module to rapresent this locations.
    '''
    store = models.ForeignKey(Store) #1 store--many location
                                        #but 1 location can have 1  store
    street = models.CharField(max_length=255) #loc addr street ex.200 main str
    city = models.CharField(max_length=64) #field for the city ex.Queens
    state = models.CharField(max_length=2) #field for the state ex.NY
    zip_code = models.CharField(max_length=5, null=True, blank=True)
     #zipcode ex.11385

    def __unicode__(self):
        return u'%s\n%s, %s, %s' % (self.street, self.city,
                                    self.state, self.zip_code)

class Product(models.Model):
    '''
    Model for the different products that are on discount.
    One product can be in discount on more the one store
    and at more them one location.
    Will need to cerate relation table for this.
    '''
    store_location = models.ManyToManyField(StoreLocation)
    product_name = models.CharField(max_length=512)
    discount_price = models.CharField(max_length=512)
    start_date = models.DateField("Deal started date:", null=True, blank=True)
    end_date = models.DateField("Deal expier date:")
    notes = models.CharField(max_length=512, null=True, blank=True)
    description = models.CharField(max_length=512, null=True, blank=True)
    product_picture = models.CharField(max_length=512, null=True, blank=True)

    def __unicode__(self):
        return self.product_name

circular/recipe/models.py
'''This module is for creating models'''
from django.db import models
#from django.utils.encoding import smart_unicode

class Recipe(models.Model):
    '''This class creates the model Recipe'''
    Cuisine_choices = (
        ("American", "American"),
        ("Italian", "Italian"),
        ("Asian", "Asian"),
        ("Mexican", "Mexican"),
        ("Southern & Soul Food", "Southern & Soul Food"),
        ("French", "French"),
        ("Indian", "Indian"),
        ("Barbecue", "Barbecue"),
        ("Cajun & Creole", "Cajun & Creole"),
        ("Chinese", "Chinese"),
        ("Mediterranean", "Mediterranean"),
        ("Greek", "Greek"),
        ("Spanish", "Spanish"),
        ("Southwestern", "Southwestern"),
        ("Japanese", "Japanese"),
        ("Irish", "Irish"),
        ("Moroccan", "Moroccan"),
        ("Hawaiin", "Hawaiin"),
        ("Swedish", "Swedish"),
        ("Hungarian", "Hungarian"),
        ("German", "German"),
        ("Portugese", "Portugese"),
        ("Thai", "Thai"),
    )
    Course_choices = (
        ("Main Dishes", "Main Dishes"),
        ("Desserts", "Desserts"),
        ("Soups", "Soups"),
        ("Breakfast and Brunch", "Breakfast and Brunch"),
        ("Breads", "Breads"),
        ("Salads", "Salads"),
        ("Appetizers", "Appetizers"),
        ("Lunch and Snacks", "Lunch and Snacks"),
        ("Side Dishes", "Side Dishes"),
        ("Cocktails", "Cocktails"),
        ("Condiments and Sauces", "Condiments and Sauces"),
        ("Beverages", "Beverages"),
    )
    Allergy_choices = (
        ("Dairy", "Dairy"),
        ("Egg", "Egg"),
        ("Gluten", "Gluten"),
        ("Peanut", "Peanut"),
        ("Seafood", "Seafood"),
        ("Sesame", "Sesame"),
        ("Soy", "Soy"),
        ("Sulfite", "Sulfite"),
        ("Tree Nut", "Tree Nut"),
    )
    Holiday_choices = (
        ("Christmas", "Christmas"),
        ("Thanksgiving", "Thanksgiving"),
        ("NewYear", "NewYear"),
        ("Super Bowl/Game Day", "Super Bowl/Game Day"),
        ("Halloween", "Halloween"),
        ("Hanukkah", "Hanukkah"),
        ("4th of July", "4th of July"),
    )
    Diet_choices = (
        ("Lacto vegetarian", "Lacto vegetarian"),
        ("Ovo vegetarian", "Ovo vegetarian"),
        ("Pescetarian", "Pescetarian"),
        ("Vegan", "Vegan"),
        ("Vegetarian", "Vegetarian"),
    )
    Flavor_choices = (
        ("meaty", "meaty"),
        ("sour", "sour"),
        ("sweet", "sweet"),
        ("salty", "salty"),
        ("piquant", "piquant"),
    )
    q = models.CharField(max_length=50,
                         blank=True, null=True)
    AllowedIngredients = models.CharField(max_length=100,
                                          blank=True, null=True)
    ExcludedIngredients = models.CharField(max_length=100,
                                           blank=True, null=True)
    cuisine = models.CharField(max_length=50, choices=Cuisine_choices,
                               blank=True, null=True)
    course = models.CharField(max_length=50, choices=Course_choices,
                              blank=True, null=True)
    Allergy = models.CharField(max_length=20, choices=Allergy_choices,
                               blank=True, null=True)
    Holiday = models.CharField(max_length=20, choices=Holiday_choices,
                               blank=True, null=True)
    Diet = models.CharField(max_length=20, choices=Diet_choices,
                            blank=True, null=True)
    flavors = models.CharField(max_length=10, choices=Flavor_choices,
                               blank=True, null=True)

circular/circular/forms.py
'''This module is for adding models and fields to the form'''
#from django import forms

circular/recipe/forms.py
'''This module is for adding models and fields to the form'''

from django import forms
from recipe.models import Recipe

class RecipeForm(forms.ModelForm):# pylint: disable=R0903
    '''This class is to add the model 'Recipe' to the Recipe form'''
    class Meta: # pylint: disable=C1001,R0903,W0232
        '''This class is used to add Recipe model to the Recipe form'''
        model = Recipe

circular/circular/views.py
'''
  This module displays all the information of deals,
  stores and products of each store
'''
from django.shortcuts import render_to_response
from django.shortcuts import RequestContext
from circular.models import Product
from circular.models import Store
from circular.models import StoreLocation
from circular.utils import make_list

def home(request):
    '''
    This view is to display link to index/ home page.
    '''
    return render_to_response("index.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def about(request):
    '''
    This view is to display link to about page.
    '''
    return render_to_response("about.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def contact(request):
    '''
    This view is to display link to contact page.
    '''
    return render_to_response("contact.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def deals(request):
    '''
    This view will be used in the deals page to display the different stores
    the store location and the products for each store.
    '''
    store = Store.objects.all()#.order_by('store_name')
    stores = make_list(db_object=store, numberc=3)
    #stores_count = stores.count()
    #store_locations = StoreLocation.objects.prefetch_related('store')
    #products = Product.objects.all()
    data = {
        'stores': stores,
        #'locations': store_locations,
        #'products': products,
        #'store_count': stores_count
        }
    return render_to_response("deals_tmp.html",
                              data,
                              context_instance=RequestContext(request)
                             )

def store_locations(request, store_id):
    '''
    This view is to display store locations.
    '''
    store = Store.objects.get(id=store_id)
    location = StoreLocation.objects.filter(store_id=store_id) # pylint: disable=E1101
    locations = make_list(db_object=location, numberc=3)
    data = {
        'store_name': store.store_name,
        'locations': locations,
        }
    return render_to_response("store_location_tmp.html",
                              data,
                              context_instance=RequestContext(request)
                             )

def products(request, store_id, location_id):
    '''
    This view is to display the products.
    '''
    store = Store.objects.get(id=store_id)
    location = StoreLocation.objects.get(id=location_id) # pylint: disable=E1101
    product = Product.objects.filter(store_location=location_id) # pylint: disable=E1101
    products = make_list(db_object=product, numberc=3) # pylint: disable=W0621
    data = {
        'store_name': store.store_name,
        'location': location,
        'products': products,
    }
    return render_to_response("products.html",
                              data,
                              context_instance=RequestContext(request)
                             )

circular/recipe/views.py
'''This module calls the yummly API, retrieves the recipe
   and displays it to the user.'''
from django.shortcuts import render_to_response
from django.shortcuts import RequestContext
from django.http import HttpResponse
import json
from yummly import Client
from recipe.forms import RecipeForm


def get_recipe(request):
    '''This function calls the yummly API and retrieves recipe data'''
    client = Client(api_id='3d16b896',
                    api_key='ad2bc866586798e1e659e988442cafb3')
    if request.method == 'POST':
        form = RecipeForm(request.POST) # pylint: disable=E1120
        #print form.errors
        if form.is_valid(): # pylint: disable=E1101
            recipe_name = request.POST.get('q', "")
            allowed_ingredients = request.POST.get('AllowedIngredients', "")
            excluded_ingredients = request.POST.get('ExcludedIngredients', "")
            allowed_cuisine = request.POST.get('allowedCuisine', "")
            allowed_course = request.POST.get('allowedCourse', "")
            options = {
                'q': recipe_name,
                'start': 0,
                'maxResult': 5,
                'requirePicutres': True,
                'allowedIngredient[]': [allowed_ingredients],
                'excludedIngredient[]': [excluded_ingredients],
                'allowedCuisine[]': [allowed_cuisine],
                'allowedCourse[]' : [allowed_course],
                'maxTotalTimeInSeconds': 3600,
                'facetField[]': ['ingredient', 'diet'],
                'flavor.sweet.min': 0,
                'flavor.sweet.max': 0.5,
                'nutrition.FAT.min': 0,
                'nutrition.FAT.max': 15
                }
            results2 = client.search(**options) # pylint: disable=W0142
            for match in results2.matches: #displaying 5 options in the terminal
                print 'Recipe ID:', match.id
                print 'Recipe:', match.recipeName
                print 'Rating:', match.rating
                for i in match.ingredients:
                    print 'Ingredients:', i
            match = results2.matches[0]
            match1 = results2.matches[1]
            recipe = client.recipe(match.id) #1st recipe
            recipe1 = client.recipe(match1.id) #2nd recipe
            print recipe
            response_dict = {}
            response_dict.update({'id': recipe.id})
            response_dict.update({'name': recipe.name})
            response_dict.update({'totalTime': recipe.totalTime})
            response_dict.update({'Ingredients': recipe.ingredientLines})
            response_dict.update({'url':  recipe.attribution.url})
            response_dict.update({'Rating': recipe.rating})
            response_dict.update({'id1': recipe1.id})
            response_dict.update({'name1': recipe1.name})
            response_dict.update({'totalTime1': recipe1.totalTime})
            response_dict.update({'Ingredients1': recipe1.ingredientLines})
            response_dict.update({'url1':  recipe1.attribution.url})
            response_dict.update({'Rating1': recipe1.rating})
            return HttpResponse(json.dumps(response_dict),
                                content_type='application/javascript')
        else:
            return HttpResponse("not valid form")
    else:
        form_recipe = RecipeForm() # pylint: disable=E1120
    ctx = {'form': form_recipe}
    return render_to_response('recipe_form.html',
                              ctx,
                              context_instance=RequestContext(request),
                             )

circular/circular/templates/Register.html
   <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Register</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/register.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-register" role="form" method='POST' action="">
        <h2 class="form-register-heading">Register Now!!</h2>
        <span style="color: rgb(255,0,0)">*</span>{{form.as_p}}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

circular/circular/templates/SignIn-temp.html
<!DOCTYPE html>
    <html>
        <head>
            
        </head>
        <body>
            <h1>Sign In</h1>
            <form method="post" action="">
                UserName:<input type="text" value="" name="User Name"/>
                <br>
                Password:<input type="text" vlaue="" name="Password"/>
                <br>
                <input type="submit" name="SignIn" value="SignIn"/>
                <input type="button" name="Cancel" value="Cancel"/>
            </form>
        </body>
    </html>

circular/circular/templates/SignIn.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Signin</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" role="form">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="email" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

circular/circular/templates/about.html
{% extends "base.html" %}

{% block title %}Weekly Circular - About{% endblock %}
{% block bootstrap %}
  <link href="{{ BASE_DIR }}/static/css/about.css" rel="stylesheet">
{% endblock %}
{% block content %}	
<div class="container">
  <div class="transbox">          
    <h3> <em>Ahoy!</em> </h3>
    <br>
      <br>
        <p>Weekly-Circular application helps the users to find food and groceries stores
        near them and display food products on discount.</p>
        <p>Based on the discounted products, we also suggest nutritious and scrumptious recipes.</p>
        <p>All of the site's resources are available to anyone, completely free of charge.</p>
      <br>
    <br>
  </div>
</div>
{% endblock %}

circular/circular/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ BASE_DIR}}/static/favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ BASE_DIR }}/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{{ BASE_DIR }}/static/css/navbar.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    
    {% block bootstrap %}
    {% endblock %}
    
  </head>
  <body>
    	{% include "navbar.html" %}
	    {% block content-carousel %}
	    {% endblock %}
	    {% block content %}
	    {% block content-related %}
	    {% endblock %}
	    {% endblock %}
	{% include "footer.html" %}
  </body>
</html>

circular/circular/templates/contact.html
{% extends "base.html" %}
{% block title %}Weekly Circular - Contact{% endblock %}
{% block bootstrap %}
<link href="{{ BASE_DIR }}/static/css/contact.css" rel="stylesheet">
{% endblock %} 

{% block content %}
<div class="container">
 <div class="transbox">
   <h3> Contact us at:</h3>
   <br>
   <br>
   <p><a href="mailto:www.weekly-circular@gmail.com">www.weekly-circular@gmail.com</a></p>
   <br>
   <br>
  </div>
 </div>
{% endblock %}
 

circular/circular/templates/deals.html
{% extends "base.html" %}

        {% block title %}Deals{% endblock %}
        {% block bootstrap %}
        <link href="{{ BASE_DIR }}/static/css/deals.css" rel="stylesheet">
        {% endblock %}

{% block content %}
  <div class="container"> 
    <br>
    <div class="sidebar">
        {% for s in stores %}
          <button type="button" class="btn btn-default btn-lg" id= {{ s }}>        
          <span class="glyphicon glyphicon-star"></span> {{ s }}  
          </button>
        {% endfor %}
    </div>
    
    {% for s in stores %}
      <div class="main-content" >
        {% for l in locations %}
          {% if s.id == l.store.id %}
            <div class='location' id={{ s }} >
              <p style="display: none;">
              {{l.street}}<br>
              {{l.city}}, {{l.state}} {{l.zip_code}}
              </p>
            </div>
            <div class = "product-content" id={{s}} >
                <i></i>
                {% for p in products %}
                  {% for i in p.store_location.iterator %}
                    {% if i.id == l.id %}
                      <li  style="display: none;">{{p.product_name}}</li>
                    {% endif %}
                  {% endfor %}
                {% endfor %}
              </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

circular/circular/templates/footer.html
<!-- FOOTER -->
<div class="container">
<footer>
<!--<p class="blue">
    
    
    </p>
<p class="text101"><em>Deals</em></p>



<p class="red">&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>

-->

<p class="pull-right"><a href="#">Back to top</a></p>
<p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>


</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/main.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/docs.min.js"></script>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

circular/circular/templates/navbar.html
<!-- NAVBAR
================================================== -->
<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Weekly Circular</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
	    <li><a href="{% url 'deals' %}">Deals</a></li>
            <li><a href="{% url 'recipe' %}">Recipes</a></li>
            <!--<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'deals' %}">Deals</a></li>
                <li><a href="{% url 'recipe' %}">Recipes</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
		-->
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
    	{% if user.is_authenticated %}
	<li><a href="{% url 'userprofile_ditail_profile' %}">Profile</a></li>
    	<li><a href="{% url 'auth_logout' %}">Log Out</a></li>
    	{% else %}
            <li><a href="{% url 'auth_login' %}">Log In</a></li>
    	<li><a href="{% url 'registration_register' %}">Register</a></li>
          {% endif %}
    	<li>&emsp;</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

circular/circular/templates/recipe_form.html
{% extends "base.html" %}
        {% block title %}Recipes{% endblock %}
        {% block bootstrap %}
        <link href="{{ BASE_DIR }}/static/css/recipeform.css" rel="stylesheet">
          <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
        {% endblock %}

{% block content %}
<div class ="container">
  <h1>User Preferences</h1>
    <form method="POST" action="{% url 'recipe' %}" id='userChoice' enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                     <label for="id_q">Recipe Name :</label>
                </td>
                <td>
                    {{form.q}}
                </td>
                <td>
                    &emsp;
                </td>
                <td>
                    <label for="id_AllowedIngredients">Allowed Ingridients :</label>
                </td>
                <td>
                    {{form.AllowedIngredients}}
                </td>
            </tr
            <tr>
                <td>
                    <label for="id_ExcludedIngredients">Exluded Ingredients :</label>
                </td>
                <td>
                    {{form.ExcludedIngredients}}
                </td>
                <td>
                    &emsp;
                </td>
                <td>
                    <label for="id_cuisine">Cuisine :</label>
                </td>
                <td>
                    {{form.cuisine}}
                </td>
            </tr>
            <tr>
                <td>
                     <label for="id_course">Course :</label>
                </td>
                <td>
                    {{form.course}}
                </td>
                <td>
                    &emsp;
                </td>
                <td>
                    <label for="id_Allergy">Allergy :</label>
                </td>
                <td>
                    {{form.Allergy}}
                </td>
            </tr>
            <tr>
                <td>
                     <label for="id_Holiday">Holiday :</label>
                </td>
                <td>
                    {{form.Holiday}}
                </td>
                <td>
                    &emsp;
                </td>
                <td>
                    <label for="id_Diet">Diet :</label>
                </td>
                <td>
                    {{form.Diet}}
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_flavors">Flavors :</label>
                </td>
                <td>
                    {{form.flavors}}
                </td>
            </tr>
            <!--<tr>
                <td>
                  <input type="text" id="fval" value="max and min values of the flavor"/>
                </td>
                <td>
                  <div id="slider-range"></div>
                </td>
            </tr>-->
        </table>
        <br>
        <table>
            <tr>
              <td>
                <input class="btn btn-primary" type="submit" value="Get Recipes" id='getRecipe'/>
              </td>
              <td>
                &emsp;
              </td>
              <td>
                <input class="btn btn-primary" type="button" value="Clear" id="clear"/>
              </td>
            </tr>
        </table>
    </form>
    <br>
    <div id="result_1" class="result"></div>
    <br>
    <div id="result_2" class="result"></div>
    <br>
</div>
{% endblock %}