circular/userprofile/urls.py
'''
Local file for the links to the user profile.
This is called int he main urls file of the project.
'''
from django.conf.urls import patterns, url

from userprofile import views

urlpatterns = patterns(  # pylint: disable=C0103
    '',
    url(r'^edit/$',
        views.update_profile,
        name='userprofile_edit_profile'),
    url(r'^$',
        views.ditail_profile,
        name='userprofile_ditail_profile'),
)

circular/weeklycircular/urls.py
'''
This is the main uarls file
'''

from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns(  # pylint: disable=C0103
    '',
    url(r'^password_change/$',
        'django.contrib.auth.views.password_change',
        {}, name='password_change'),
    url(r'^password_change_done/$',
        'django.contrib.auth.views.password_change_done',
        {}, name='password_change_done'),
    url(r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        {}, 'password_reset'),
    url(r'^password_reset_done/$',
        'django.contrib.auth.views.password_reset_done',
        {}, 'password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>.+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {}, 'password_reset_confirm'),
    url(r'^password_reset_complete/$',
        'django.contrib.auth.views.password_reset_complete',
        {}, 'password_reset_complete'),
    url(r'^accounts/profile/', include('userprofile.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'circular.views.home', name='home'),
    url(r'^about/$', 'circular.views.about', name='about'),
    url(r'^contact/$', 'circular.views.contact', name='contact'),
    url(r'^deals/$', 'circular.views.deals', name='deals'),
    url(r'^recipe/$', 'recipe.views.get_recipe', name='recipe'),
    url(r'^deals/(?P<store_id>[0-9]+)/$',
        'circular.views.store_locations',
        name='locations'),
    url(r'^deals/(?P<store_id>[0-9]+)/(?P<location_id>[0-9]+)/$',
        'circular.views.products',
        name='products'),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

circular/circular/models.py
'''This module is for adding models and fields to the form'''
from django.db import models

class Store(models.Model):
    '''
    This model is for the store her we
    have one store with the store name and a logo.
    '''
    store_name = models.CharField(max_length=128) #Field for storename eg.shop
    store_logo = models.CharField(
        max_length=512,
        null=True,
        blank=True
        )
    objects = models.Manager() # pylint: disable=E1120
    # Field to hold the store logo

    def __unicode__(self):
        return self.store_name

class StoreLocation(models.Model):
    '''
    Each store can have multiple location. so we have
    this module to rapresent this locations.
    '''
    store = models.ForeignKey(Store) #1 store--many location
                                        #but 1 location can have 1  store
    street = models.CharField(max_length=255) #loc addr street ex.200 main str
    city = models.CharField(max_length=64) #field for the city ex.Queens
    state = models.CharField(max_length=2) #field for the state ex.NY
    zip_code = models.CharField(max_length=5, null=True, blank=True)
     #zipcode ex.11385

    def __unicode__(self):
        return u'%s\n%s, %s, %s' % (self.street, self.city,
                                    self.state, self.zip_code)

class Product(models.Model):
    '''
    Model for the different products that are on discount.
    One product can be in discount on more the one store
    and at more them one location.
    Will need to cerate relation table for this.
    '''
    store_location = models.ManyToManyField(StoreLocation)
    product_name = models.CharField(max_length=512)
    discount_price = models.CharField(max_length=512)
    start_date = models.DateField("Deal started date:", null=True, blank=True)
    end_date = models.DateField("Deal expier date:")
    notes = models.CharField(max_length=512, null=True, blank=True)
    description = models.CharField(max_length=512, null=True, blank=True)
    product_picture = models.CharField(max_length=512, null=True, blank=True)

    def __unicode__(self):
        return self.product_name

circular/userprofile/models.py
'''
   This module has models and other helper function
               for the user profile.
'''
from django.db import models
from django.contrib.auth.models import User
#from django.contrib.auth.models import BaseUserManager
#from django.contrib.auth.models import AbstractBaseUser
from django.core.exceptions import ValidationError

def zip_validate(zip_code):
    '''
       Function to validate the zip code which should be
                   numberic and 5 digit long.
    '''
    if len(zip_code) == 5:
        try:
            int(zip_code)
        except:
            raise ValidationError("You can input only numbers in this field")
    else:
        raise ValidationError("The value in this field has to be 5 digit long")

class UserProfile(models.Model):
    '''
       Model for user profile preferances.
    '''
    Allergy_choices = (
        ("N/A", "N/A"),
        ("Dairy", "Dairy"),
        ("Egg", "Egg"),
        ("Gluten", "Gluten"),
        ("Peanut", "Peanut"),
        ("Seafood", "Seafood"),
        ("Sesame", "Sesame"),
        ("Soy", "Soy"),
        ("Sulfite", "Sulfite"),
        ("Tree Nut", "Tree Nut"),
    )
    Diet_choices = (
        ("N/A", "N/A"),
        ("Lacto vegetarian", "Lacto vegetarian"),
        ("Ovo vegetarian", "Ovo vegetarian"),
        ("Pescetarian", "Pescetarian"),
        ("Vegan", "Vegan"),
        ("Vegetarian", "Vegetarian"),
    )
    user = models.OneToOneField(User)
    zip_code = models.CharField(max_length=5,
                                blank=True,
                                null=True,
                                validators=[zip_validate])
    allergy = models.CharField(max_length=20,
                               default='N/A',
                               choices=Allergy_choices)
    diet = models.CharField(max_length=20,
                            default='N/A',
                            choices=Diet_choices)

    def __unicode__(self):
        return u"Profile for %s" % self.user

#User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

circular/circular/forms.py
'''This module is for adding models and fields to the form'''
#from django import forms

circular/circular/views.py
'''
  This module displays all the information of deals,
  stores and products of each store
'''
from django.shortcuts import render_to_response
from django.shortcuts import RequestContext
from circular.models import Product
from circular.models import Store
from circular.models import StoreLocation
from circular.utils import make_list

def home(request):
    '''
    This view is to display link to index/ home page.
    '''
    return render_to_response("index.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def about(request):
    '''
    This view is to display link to about page.
    '''
    return render_to_response("about.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def contact(request):
    '''
    This view is to display link to contact page.
    '''
    return render_to_response("contact.html",
                              locals(),
                              context_instance=RequestContext(request)
                             )
def deals(request):
    '''
    This view will be used in the deals page to display the different stores
    the store location and the products for each store.
    '''
    store = Store.objects.all()#.order_by('store_name')
    stores = make_list(db_object=store, numberc=3)
    #stores_count = stores.count()
    #store_locations = StoreLocation.objects.prefetch_related('store')
    #products = Product.objects.all()
    data = {
        'stores': stores,
        #'locations': store_locations,
        #'products': products,
        #'store_count': stores_count
        }
    return render_to_response("deals_tmp.html",
                              data,
                              context_instance=RequestContext(request)
                             )

def store_locations(request, store_id):
    '''
    This view is to display store locations.
    '''
    store = Store.objects.get(id=store_id)
    location = StoreLocation.objects.filter(store_id=store_id) # pylint: disable=E1101
    locations = make_list(db_object=location, numberc=3)
    data = {
        'store_name': store.store_name,
        'locations': locations,
        }
    return render_to_response("store_location_tmp.html",
                              data,
                              context_instance=RequestContext(request)
                             )

def products(request, store_id, location_id):
    '''
    This view is to display the products.
    '''
    store = Store.objects.get(id=store_id)
    location = StoreLocation.objects.get(id=location_id) # pylint: disable=E1101
    product = Product.objects.filter(store_location=location_id) # pylint: disable=E1101
    products = make_list(db_object=product, numberc=3) # pylint: disable=W0621
    data = {
        'store_name': store.store_name,
        'location': location,
        'products': products,
    }
    return render_to_response("products.html",
                              data,
                              context_instance=RequestContext(request)
                             )

circular/circular/templates/profiles/avatar.html
{% load thumbnail %}

{% comment %}
	If profile has an avatar, show it.
	If user is viewing their own list and they don't have an avatar, 
	show them the Add Photo button. Otherwise show generic avatar.
{% endcomment %}



<div class="avatar">
	
    {% if profile.avatar %}

	{% thumbnail profile.avatar "100x100" crop="center" as im %}
	    <a href="{% url list_view profile.user.username %}"><img src="{{im.url}}" width="{{im.width}}" height="{{im.height}}" alt="{{profile}}'s avatar image" /></a>
	{% endthumbnail %}


	{% else %}
		{% if profile == user.get_profile %}
			<a href="{% url profiles_edit_profile %}"><img src="{{ MEDIA_URL }}images/no-photo.png" width="100" height="100" alt="Please add an avatar to your profile."></a>
			{% else %}
			<a href="{% url list_view profile.user.username %}"><img src="{{ STATIC_URL }}images/user_default_medium.png" width="100" height="100" alt="Generic avatar"></a>
		{% endif %}
	
	{% endif %}

</div>

circular/circular/templates/profiles/create_profile.html
{% extends "base.html" %}
{% block content%}

<script>
 $(document).ready(function() {
   $("#profile").addClass("active");
 });
</script>

<div class="container">
    <h2>Create Profile:</h2>
 
<h2>{{ user|capfirst }}, before we begin, lets set some of your account preferences. These can be changed at any time.</h2>
 
<form method="POST" action="">
        <p>
            Default League to bet: <span class="required">*</span>  {{ form.pref_sport }}
            {% for error in form.pref_sport.errors %}
                {{ error|escape }}
            {% endfor %}
        </p>

        <p>
            Default Number of games to bet: <span class="required">*</span>  {{ form.pref_num_games }}
            {% for error in form.pref_num_games.errors %}
                {{ error|escape }}
            {% endfor %}
        </p>

    <input type="submit" name="submit" class="submit" value="Create Profile">
</form>
</div>
 
{% endblock %}

circular/circular/templates/profiles/detail_profile.html
{% extends "base.html" %}

{% block title %} {{ user.first_name }} {{ user.last_name }}{% endblock %}

{% block bootstrap %}
  <link href="{{ BASE_DIR }}/static/css/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

<h2>Hello {{ user }}</h2>

<div class="row">
<div class="col-md-4">
  <dd><a class="btn btn-primary" href="{% url 'userprofile_edit_profile' %}">Edit Profile</a></dd>
  <p></p>
  <dd><a class="btn btn-primary" href="{% url 'auth_password_change' %}">Change Password</a></dd>
</div>
<div class="col-md-4">
  <h3>User Profile:</h3>
  <dl>
    <dt>
      <label class="form-signin-heading" for="id_firstname">First Name:</label>
    </dt>
    <dd>{{ user.first_name }}</dd>
    <dt>
      <label class="form-signin-heading" for="id_last_name">Last Name:</label>
    </dt>
    <dd>{{ user.last_name }}</dd>
    <dt>
      <label class="form-signin-heading" for="id_email">E-mail:</label>
    <dd>{{ user.email }}</dd>
    <dt>
      <label class="form-signin-heading" for="id_zip_code">Zip Code:</label>
    </dt>
    <dd>{{ user.userprofile.zip_code }}</dd>
    <dt>
      <label class="form-signin-heading" for="id_allergy">Allergy:</label>
    </dt>
    <dd>{{ user.userprofile.allergy }}</dd>
    <dt>
      <label class="form-signin-heading" for="id_diet">Diet:</label>
    </dt>
    <dd>{{ user.userprofile.diet }}</dd>
  </dl>
</div>
</div>
</div>

{% endblock content %}

circular/circular/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block bootstrap %}
  <link href="{{ BASE_DIR }}/static/css/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}

{# Hidden divs - revealed by jquery dialog #}
<div class="container">

<h2>Hello {{ user }}</h2>


<h3>User Profile:</h3> 
{% if form.errors or formuser.errors %}
  <p class="errors">Please correct the errors below:</p>
{% endif %}


<form class="form-sigin" role="form" method="post" action="" class="wide">{% csrf_token %}
  <dl>
  <dt>
    <label class="form-signin-heading" for="id_firstname">First Name:</label>
    {% if form.first_name.errors %} 
      <span class="error">{{ form.first_name.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ form.first_name }}</dd>
  <dt>
    <label class="form-signin-heading" for="id_last_name">Last Name:</label>
    {% if form.last_name.errors %} 
       <span class="error">{{ form.last_name.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ form.last_name }}</dd>
  <dt>
    <label class="form-signin-heading" for="id_email">E-mail:</label>
    {% if form.email.errors %} 
       <span class="error">{{ form.email.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ form.email }}</dd>
  <dt>
    <label class="form-signin-heading" for="id_zip_code">Zip Code:</label>
    {% if formuser.zip_code.errors %} 
       <span class="error">{{ formuser.zip_code.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ formuser.zip_code }}</dd>
  <dt>
    <label class="form-signin-heading" for="id_allergy">Allergy:</label>
    {% if formuser.allergy.errors %} 
       <span class="error">{{ formuser.allergy.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ formuser.allergy }}</dd>
  <dt>
    <label class="form-signin-heading" for="id_diet">Diet:</label>
    {% if formuser.diet.errors %} 
       <span class="error">{{ formuser.diet.errors|join:", " }}</span>
    {% endif %}
  </dt>
  <dd>{{ formuser.diet }}</dd>
  <dt>
    <input class="btn btn-primary" type="submit" value="Update" />
    <a class="btn btn-primary" href="{% url 'userprofile_ditail_profile' %}">Go Back</a>
  </dt>
  </dl>
</form>

</div>

{% endblock content %}

circular/circular/templates/profiles/edit_settings.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}Edit Profile Settings{% endblock %}


{% block content %}

{% if form.errors %}
	<ul id="messagelist">
		<p>The following required fields are missing:</p>
		{% for error in form.errors %}
		<li class="error">{{ error }}</li>
		{% endfor %}
	</ul>
{% endif %}


<h2>Edit settings for {{ user.first_name }} {{ user.last_name }} ({{user}})</h2>


<div class="clear"></div>

<form enctype="multipart/form-data" method="post" action="" style="margin-top:20px;">

	{% csrf_token %}

	<p>We recommend  keeping all of these settings enabled. <br />
		Don't worry - none of them will result in a ton of email!</p>

	<div class="fieldWrapper inline">
	{{form.use_full_name}} {{form.use_full_name.label_tag}}<br />
	<span style="margin-left:25px;">{{form.use_full_name.help_text}}</span>
	</div>
		
	<div class="fieldWrapper inline">
	{{form.email_updates}} {{form.email_updates.label_tag}}
	</div>
	
	<div class="fieldWrapper inline">
	{{form.email_on_follow}} {{form.email_on_follow.label_tag}}
	</div>
	
	<div class="fieldWrapper inline">
	{{form.email_on_copy}} {{form.email_on_copy.label_tag}}
	</div>		
	
	<div class="fieldWrapper inline">
	{{form.email_site_news}} {{form.email_site_news.label_tag}}
	</div>	
	
	<div class="fieldWrapper inline">
	{{form.allow_contact}} {{form.allow_contact.label_tag}}
	</div>	
	
	<div class="fieldWrapper inline">
	{{form.enable_comments}} {{form.enable_comments.label_tag}}
	</div>		
	
			
	
	<p style="margin-top:30px;"><input class="button blue" type="submit" value="Update settings" /> </p>

	<p>
		<a href="/accounts/password/change/" class="button medium green">&raquo; Change my password &laquo;</a> 
		<a href="{% url profiles_edit_profile %}" class="button medium green">&raquo; Update profile &laquo;</a> 		
	</p>

</form>
{% endblock content %}

circular/circular/templates/profiles/profile_list.html
{% extends "base.html" %}


{% block title %}Contact info for {{ user.first_name }} {{ user.last_name }}{% endblock %}

{% block content %}

{{block.super}}

{% for p in object_list  %}
	<a href="{% url profiles_profile_detail p.user %}">{{ p }}</a><br />
{% endfor %}

{% endblock content %}